version: "3.7"
services:
    rabbitmq:
        image: rabbitmq:3.7-alpine

    webhooks:
        build: .
        env_file: .env
        environment: 
            NODEID: "node-webhooks"
            SERVICES: webhooks 
            PORT: 27017
        depends_on:
            - mongodb
            - rabbitmq
    
    backend:
        build: .
        env_file: .env
        environment: 
            NODEID: "node-backend"
            SERVICES: backend
            PORT: 3000
        ports:
            - 3000:3000
        depends_on:
            - rabbitmq
            - webhooks

    mongodb:
        image: mongo:latest
        ports:
            - 27017:27017
        volumes:
            - data:/data/db
        depends_on: 
            - rabbitmq

volumes: 
    data: