const mongoose = require("mongoose");

//Create the database model for webhooks
mongoose.model("webhook", {
    ID: { //this the id generated by the service
        type: String,
        require: true
    },

    targetUrl: { //this is the url passed by the user
        type: String,
        require: true
    }
});